"""
Email tool — send offer directly from chat to client.
Uses smtplib (stdlib). Configure SMTP_* vars in .env
"""
import os
import sqlite3
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from datetime import datetime

try:
    from fastmcp import FastMCP
    mcp = FastMCP("insurance-broker-mcp-email")
except Exception:
    mcp = None

DB_PATH = Path(__file__).parent.parent.parent / "insurance_broker.db"
OUTPUT_DIR = Path(__file__).parent.parent.parent / "output"

SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
SMTP_FROM_NAME = os.environ.get("SMTP_FROM_NAME", "Alex Insurance Broker")


def send_offer_email_fn(offer_id: str, to_email: str = None, subject: str = None) -> str:
    """
    Send a generated offer by email to the client.
    If to_email not provided, fetches client email from DB.
    """
    if not SMTP_USER or not SMTP_PASS:
        return (
            "⚠️ Email not configured. Add SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS to .env\n"
            "For Gmail: use an App Password (myaccount.google.com/apppasswords)"
        )

    try:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row

        # Find the offer
        offer = conn.execute(
            "SELECT o.*, c.name as client_name, c.email as client_email "
            "FROM offers o JOIN clients c ON o.client_id = c.id WHERE o.id = ?",
            (offer_id,)
        ).fetchone()

        if not offer:
            conn.close()
            return f"❌ Offer {offer_id} not found. Use broker_list_offers to see available offers."

        recipient = to_email or offer["client_email"]
        if not recipient:
            conn.close()
            return f"❌ No email found for client {offer['client_name']}. Provide to_email parameter."

        # Find offer file
        offer_files = list(OUTPUT_DIR.glob(f"*{offer_id[-8:]}*.txt"))
        if not offer_files:
            # Try by client name
            safe_name = offer["client_name"].replace(" ", "_")
            offer_files = sorted(OUTPUT_DIR.glob(f"{safe_name}*.txt"), key=lambda f: f.stat().st_mtime, reverse=True)

        # Build email
        msg = MIMEMultipart("alternative")
        msg["From"] = f"{SMTP_FROM_NAME} <{SMTP_USER}>"
        msg["To"] = recipient
        msg["Subject"] = subject or f"Insurance Offer — {offer['client_name']} | {offer_id}"

        html_body = f"""
<html><body style="font-family: Arial, sans-serif; color: #333; max-width: 600px;">
<div style="background: #1a365d; padding: 20px; border-radius: 8px 8px 0 0;">
  <h2 style="color: white; margin: 0;">🛡️ Insurance Offer</h2>
  <p style="color: #a0aec0; margin: 5px 0 0;">Alex — Insurance Broker AI</p>
</div>
<div style="padding: 20px; border: 1px solid #e2e8f0; border-radius: 0 0 8px 8px;">
  <p>Dear <strong>{offer["client_name"]}</strong>,</p>
  <p>Please find attached your personalized insurance offer prepared by our team.</p>
  <table style="width:100%; border-collapse:collapse; margin: 15px 0;">
    <tr style="background:#f7fafc;">
      <td style="padding:8px; border:1px solid #e2e8f0;"><strong>Offer ID</strong></td>
      <td style="padding:8px; border:1px solid #e2e8f0;">{offer_id}</td>
    </tr>
    <tr>
      <td style="padding:8px; border:1px solid #e2e8f0;"><strong>Valid Until</strong></td>
      <td style="padding:8px; border:1px solid #e2e8f0;">{offer.get("valid_until", "30 days from issue")}</td>
    </tr>
    <tr style="background:#f7fafc;">
      <td style="padding:8px; border:1px solid #e2e8f0;"><strong>Products</strong></td>
      <td style="padding:8px; border:1px solid #e2e8f0;">{offer.get("products_count", 1)} insurance product(s)</td>
    </tr>
  </table>
  <p>Please review the attached offer and contact us with any questions.</p>
  <p>We remain at your disposal for any clarifications regarding coverage, terms, or pricing.</p>
  <hr style="border:none; border-top:1px solid #e2e8f0; margin:20px 0;">
  <p style="color:#718096; font-size:12px;">
    This offer was prepared in compliance with ASF (Law 236/2018) and BaFin (VVG/IDD) regulations.<br>
    Offer generated by Alex — Insurance Broker AI | Powered by Google Gemini 2.5 Pro
  </p>
</div>
</body></html>
"""
        msg.attach(MIMEText(html_body, "html"))

        # Attach offer file if found
        attachment_name = None
        if offer_files:
            offer_file = offer_files[0]
            attachment_name = offer_file.name
            with open(offer_file, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header("Content-Disposition", f'attachment; filename="{offer_file.name}"')
                msg.attach(part)

        # Send
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, recipient, msg.as_string())

        # Update offer status to "sent" in DB
        conn.execute(
            "UPDATE offers SET status = 'sent' WHERE id = ?",
            (offer_id,)
        )
        conn.commit()
        conn.close()

        result = f"""✅ **Offer sent successfully!**

| Field | Value |
|---|---|
| **To** | {recipient} |
| **Client** | {offer["client_name"]} |
| **Offer ID** | {offer_id} |
| **Sent at** | {datetime.now().strftime("%d %b %Y %H:%M")} |
| **Attachment** | {attachment_name or "No file attached"} |

Offer status updated to **sent** in the system."""

        return result

    except smtplib.SMTPAuthenticationError:
        return "❌ SMTP authentication failed. Check SMTP_USER and SMTP_PASS in .env"
    except smtplib.SMTPException as e:
        return f"❌ Email sending failed: {e}"
    except Exception as e:
        return f"❌ Error: {type(e).__name__}: {e}"


if mcp:
    @mcp.tool(name="broker_send_offer_email")
    def broker_send_offer_email(offer_id: str, to_email: str = None, subject: str = None) -> str:
        """
        Send a generated offer by email directly to the client.
        Fetches client email from database if to_email not provided.
        Attaches the offer document and updates status to 'sent'.
        """
        return send_offer_email_fn(offer_id=offer_id, to_email=to_email, subject=subject)
