"""
Email tool — send offer directly from chat to client.
Uses smtplib (stdlib). Configure SMTP_* vars in .env
"""
import os
import sqlite3
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from datetime import datetime

try:
    from fastmcp import FastMCP
    mcp = FastMCP("insurance-broker-mcp-email")
except Exception:
    mcp = None

DB_PATH = Path(__file__).parent.parent.parent / "insurance_broker.db"
OUTPUT_DIR = Path(__file__).parent.parent.parent / "output"

SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
try:
    SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
except ValueError:
    SMTP_PORT = 587
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
SMTP_FROM_NAME = os.environ.get("SMTP_FROM_NAME", "Alex Insurance Broker")

# ── Localization strings ───────────────────────────────────────────────────────
_L = {
    "ro": {
        "subject":    "Ofertă de Asigurare — {client_name} | {offer_id}",
        "title":      "🛡️ Ofertă de Asigurare",
        "subtitle":   "Alex — Broker de Asigurări AI",
        "dear":       "Stimate/ă <strong>{client_name}</strong>,",
        "intro":      "Vă transmitem alăturat oferta personalizată de asigurare pregătită de echipa noastră.",
        "lbl_id":     "Nr. Ofertă",
        "lbl_valid":  "Valabilă până la",
        "lbl_prods":  "Produse",
        "lbl_prods_val": "{n} produs(e) de asigurare",
        "review":     "Vă rugăm să analizați oferta atașată și să ne contactați pentru orice clarificare.",
        "available":  "Suntem la dispoziția dumneavoastră pentru orice întrebări privind acoperirea, condițiile sau prețurile.",
        "footer":     "Ofertă pregătită în conformitate cu reglementările ASF (Legea 236/2018) și BaFin (VVG/IDD).<br>Generată de Alex — Broker AI",
    },
    "de": {
        "subject":    "Versicherungsangebot — {client_name} | {offer_id}",
        "title":      "🛡️ Versicherungsangebot",
        "subtitle":   "Alex — KI-Versicherungsmakler",
        "dear":       "Sehr geehrte/r <strong>{client_name}</strong>,",
        "intro":      "Anbei finden Sie Ihr persönliches Versicherungsangebot, das von unserem Team vorbereitet wurde.",
        "lbl_id":     "Angebots-Nr.",
        "lbl_valid":  "Gültig bis",
        "lbl_prods":  "Produkte",
        "lbl_prods_val": "{n} Versicherungsprodukt(e)",
        "review":     "Bitte prüfen Sie das beigefügte Angebot und kontaktieren Sie uns bei Fragen.",
        "available":  "Wir stehen Ihnen für alle Fragen zu Deckung, Bedingungen und Preisen gerne zur Verfügung.",
        "footer":     "Angebot gemäß ASF (Gesetz 236/2018) und BaFin (VVG/IDD).<br>Erstellt von Alex — KI-Makler",
    },
    "en": {
        "subject":    "Insurance Offer — {client_name} | {offer_id}",
        "title":      "🛡️ Insurance Offer",
        "subtitle":   "Alex — Insurance Broker AI",
        "dear":       "Dear <strong>{client_name}</strong>,",
        "intro":      "Please find attached your personalized insurance offer prepared by our team.",
        "lbl_id":     "Offer ID",
        "lbl_valid":  "Valid Until",
        "lbl_prods":  "Products",
        "lbl_prods_val": "{n} insurance product(s)",
        "review":     "Please review the attached offer and contact us with any questions.",
        "available":  "We remain at your disposal for any clarifications regarding coverage, terms, or pricing.",
        "footer":     "Offer prepared in compliance with ASF (Law 236/2018) and BaFin (VVG/IDD) regulations.<br>Generated by Alex — Insurance Broker AI",
    },
}


def _detect_language_from_file(file_path: Path) -> str:
    """Detect language from offer file content."""
    try:
        text = file_path.read_text(encoding="utf-8")[:500]
        if "Ofertă de Asigurare" in text or "Stimate" in text or "Primă anuală" in text:
            return "ro"
        if "Versicherungsangebot" in text or "Sehr geehrte" in text or "Jahresprämie" in text:
            return "de"
    except Exception:
        pass
    return "en"


def send_offer_email_fn(offer_id: str, to_email: str = None, subject: str = None, language: str = None) -> str:
    """
    Send a generated offer by email to the client.
    If to_email not provided, fetches client email from DB.
    language: 'ro', 'de', 'en' — auto-detected from offer file if not set.
    """
    if not SMTP_USER or not SMTP_PASS:
        return (
            "⚠️ Email not configured. Add SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS to .env\n"
            "For Gmail: use an App Password (myaccount.google.com/apppasswords)"
        )

    try:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row

        # Find the offer in DB
        offer = conn.execute(
            "SELECT o.*, c.name as client_name, c.email as client_email "
            "FROM offers o JOIN clients c ON o.client_id = c.id WHERE o.id = ?",
            (offer_id,)
        ).fetchone()

        # Resolve recipient and client name
        if offer:
            recipient = to_email or offer["client_email"]
            client_name = offer["client_name"]
            valid_until = offer["valid_until"] if offer["valid_until"] else "30 days from issue"
            products_count = offer["products_count"] if offer["products_count"] else 1
        else:
            # Offer not in DB (e.g. created in previous container session on Cloud Run)
            if not to_email:
                conn.close()
                return (
                    f"❌ Oferta {offer_id} nu a fost găsită în baza de date.\n"
                    f"Furnizați adresa email explicit: broker_send_offer_email(offer_id='{offer_id}', to_email='client@example.com')"
                )
            recipient = to_email
            client_name = "Client"
            valid_until = "30 days from issue"
            products_count = 1

        if not recipient:
            conn.close()
            return "❌ Nu există email pentru client. Furnizați parametrul to_email."

        # Find offer file — prefer PDF, fallback to TXT
        offer_file = None
        attachment_name = None

        # Search PDF first
        pdf_files = list(OUTPUT_DIR.glob(f"*{offer_id}*.pdf"))
        if not pdf_files:
            pdf_files = list(OUTPUT_DIR.glob(f"*{offer_id[-8:]}*.pdf"))
        if pdf_files:
            offer_file = pdf_files[0]

        # Fallback to TXT
        if not offer_file:
            txt_files = list(OUTPUT_DIR.glob(f"*{offer_id}*.txt"))
            if not txt_files:
                txt_files = list(OUTPUT_DIR.glob(f"*{offer_id[-8:]}*.txt"))
            if not txt_files and offer:
                safe_name = client_name.replace(" ", "_")
                txt_files = sorted(
                    OUTPUT_DIR.glob(f"{safe_name}*.txt"),
                    key=lambda f: f.stat().st_mtime, reverse=True
                )
            if txt_files:
                offer_file = txt_files[0]

        # Auto-detect language from file, or use provided language
        lang = language or (
            _detect_language_from_file(offer_file) if offer_file else "ro"
        )
        if lang not in _L:
            lang = "ro"
        t = _L[lang]

        # Build email
        msg = MIMEMultipart("mixed")
        msg["From"] = f"{SMTP_FROM_NAME} <{SMTP_USER}>"
        msg["To"] = recipient
        msg["Subject"] = subject or t["subject"].format(client_name=client_name, offer_id=offer_id)

        html_body = f"""
<html><body style="font-family: Arial, sans-serif; color: #333; max-width: 620px; margin: 0 auto;">
<div style="background: linear-gradient(135deg, #1a365d 0%, #2a4a7f 100%); padding: 24px 28px; border-radius: 10px 10px 0 0;">
  <h2 style="color: white; margin: 0; font-size: 20px;">{t["title"]}</h2>
  <p style="color: #a0aec0; margin: 6px 0 0; font-size: 13px;">{t["subtitle"]}</p>
</div>
<div style="padding: 24px 28px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 10px 10px; background: #fff;">
  <p style="margin-top:0;">{t["dear"].format(client_name=client_name)}</p>
  <p>{t["intro"]}</p>
  <table style="width:100%; border-collapse:collapse; margin: 18px 0; font-size: 14px;">
    <tr style="background:#f7fafc;">
      <td style="padding:10px 12px; border:1px solid #e2e8f0; font-weight:600; width:40%;">{t["lbl_id"]}</td>
      <td style="padding:10px 12px; border:1px solid #e2e8f0;">{offer_id}</td>
    </tr>
    <tr>
      <td style="padding:10px 12px; border:1px solid #e2e8f0; font-weight:600;">{t["lbl_valid"]}</td>
      <td style="padding:10px 12px; border:1px solid #e2e8f0;">{valid_until}</td>
    </tr>
    <tr style="background:#f7fafc;">
      <td style="padding:10px 12px; border:1px solid #e2e8f0; font-weight:600;">{t["lbl_prods"]}</td>
      <td style="padding:10px 12px; border:1px solid #e2e8f0;">{t["lbl_prods_val"].format(n=products_count)}</td>
    </tr>
  </table>
  <p>{t["review"]}</p>
  <p>{t["available"]}</p>
  <hr style="border:none; border-top:1px solid #e2e8f0; margin:20px 0;">
  <p style="color:#718096; font-size:11px; line-height:1.6;">
    {t["footer"]}
  </p>
</div>
</body></html>
"""
        alt_part = MIMEMultipart("alternative")
        alt_part.attach(MIMEText(html_body, "html", "utf-8"))
        msg.attach(alt_part)

        # Attach offer file (PDF preferred, TXT fallback)
        if offer_file:
            attachment_name = offer_file.name
            mime_type = "application/pdf" if offer_file.suffix == ".pdf" else "application/octet-stream"
            with open(offer_file, "rb") as f:
                part = MIMEBase(*mime_type.split("/"))
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header("Content-Disposition", f'attachment; filename="{offer_file.name}"')
                msg.attach(part)

        # Send
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.sendmail(SMTP_USER, recipient, msg.as_string())

        # Update offer status to "sent" in DB (only if found)
        if offer:
            conn.execute("UPDATE offers SET status = 'sent' WHERE id = ?", (offer_id,))
            conn.commit()
        conn.close()

        attach_label = attachment_name or ("Fără atașament" if lang == "ro" else "No file attached")
        result = f"""✅ **Email trimis cu succes!**

| Câmp | Valoare |
|---|---|
| **Destinatar** | {recipient} |
| **Client** | {client_name} |
| **Nr. Ofertă** | {offer_id} |
| **Trimis la** | {datetime.now().strftime("%d %b %Y %H:%M")} |
| **Atașament** | {attach_label} |

Statusul ofertei actualizat la **trimis** în sistem."""

        return result

    except smtplib.SMTPAuthenticationError:
        return "❌ Autentificare SMTP eșuată. Verificați SMTP_USER și SMTP_PASS."
    except smtplib.SMTPException as e:
        return f"❌ Trimitere email eșuată: {e}"
    except Exception as e:
        return f"❌ Eroare: {type(e).__name__}: {e}"


if mcp:
    @mcp.tool(name="broker_send_offer_email")
    def broker_send_offer_email(offer_id: str, to_email: str = None, subject: str = None, language: str = None) -> str:
        """
        Send a generated offer by email directly to the client.
        Fetches client email from database if to_email not provided.
        Attaches the offer document (PDF if available, otherwise TXT) and updates status to 'sent'.
        language: 'ro', 'de', 'en' — auto-detected if not provided.
        """
        return send_offer_email_fn(offer_id=offer_id, to_email=to_email, subject=subject, language=language)
